/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"

// generated by default, solve later if need be
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void SystemClock_Config(void);
void GPIO_Setup(void);

int main(void)
{
	/* MPU Setup */
	LL_APB2_GRP1_EnableClock(LL_APB2_GRP1_PERIPH_SYSCFG);
	LL_APB1_GRP1_EnableClock(LL_APB1_GRP1_PERIPH_PWR);
	NVIC_SetPriorityGrouping((uint32_t)0x00000003); // Priority Group 4
	LL_PWR_DisableUCPDDeadBattery();
	SystemClock_Config();

	GPIO_Setup();

	while(1) {
		LL_GPIO_ResetOutputPin(GPIOA, LL_GPIO_PIN_5);
		LL_mDelay(400);
		LL_GPIO_SetOutputPin(GPIOA, LL_GPIO_PIN_5);
		LL_mDelay(10);
	}
}


// User Button is on GPIO PC13 default (SB16 ON / SB21 OFF), PA0 optionally (SB16 OFF / SB21 ON)
// User LED is on GPIO PA5, write hi

/*
 * UART setup:
 * 	Tx:	PA5		CN10 p11
 * 	Rx:	PA6		CN10 p13
 * 	G:	n/a 	CN10 p9
 * 	5V: n/a		CN7  p18
 */

void GPIO_Setup(void) {
	// enable clock
	LL_AHB2_GRP1_EnableClock(LL_AHB2_GRP1_PERIPH_GPIOA);

	LL_GPIO_InitTypeDef initStruct = {
			LL_GPIO_PIN_5,
			LL_GPIO_MODE_OUTPUT,
			LL_GPIO_OUTPUT_PUSHPULL,
			LL_GPIO_SPEED_FREQ_LOW,
			LL_GPIO_PULL_DOWN,
			LL_GPIO_AF_0,
	};
	LL_GPIO_Init(GPIOA, &initStruct);
}

/*
 * System Clock Configuration
 * pulled right from CubeMX example
 */
void SystemClock_Config(void)
{
	LL_FLASH_SetLatency(LL_FLASH_LATENCY_4);
	while(LL_FLASH_GetLatency() != LL_FLASH_LATENCY_4)
	{
	}
	LL_PWR_EnableRange1BoostMode();
	LL_RCC_HSI_Enable();
	/* Wait till HSI is ready */
	while(LL_RCC_HSI_IsReady() != 1)
	{
	}

	LL_RCC_HSI_SetCalibTrimming(64);
	LL_RCC_PLL_ConfigDomain_SYS(LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_4, 85, LL_RCC_PLLR_DIV_2);
	LL_RCC_PLL_EnableDomain_SYS();
	LL_RCC_PLL_Enable();
	/* Wait till PLL is ready */
	while(LL_RCC_PLL_IsReady() != 1)
	{
	}

	LL_RCC_SetSysClkSource(LL_RCC_SYS_CLKSOURCE_PLL);
	LL_RCC_SetAHBPrescaler(LL_RCC_SYSCLK_DIV_2);
	/* Wait till System clock is ready */
	while(LL_RCC_GetSysClkSource() != LL_RCC_SYS_CLKSOURCE_STATUS_PLL)
	{
	}

	/* Insure 1us transition state at intermediate medium speed clock*/
	for (__IO uint32_t i = (170 >> 1); i !=0; i--);

	/* Set AHB prescaler*/
	LL_RCC_SetAHBPrescaler(LL_RCC_SYSCLK_DIV_1);
	LL_RCC_SetAPB1Prescaler(LL_RCC_APB1_DIV_1);
	LL_RCC_SetAPB2Prescaler(LL_RCC_APB2_DIV_1);

	LL_Init1msTick(170000000);

	LL_SetSystemCoreClock(170000000);
}
